"""
Lista dei costituenti del Nasdaq-100 (simbolo -> nome).

La composizione dell'indice cambia nel tempo: questa e' una lista
rappresentativa e facilmente aggiornabile. Anche se qualche titolo dovesse
essere entrato/uscito, i simboli restano validi per il download dei dati.
"""

NASDAQ_100 = {
    "AAPL": "Apple",
    "MSFT": "Microsoft",
    "AMZN": "Amazon",
    "NVDA": "NVIDIA",
    "GOOGL": "Alphabet (A)",
    "GOOG": "Alphabet (C)",
    "META": "Meta Platforms",
    "AVGO": "Broadcom",
    "TSLA": "Tesla",
    "COST": "Costco",
    "NFLX": "Netflix",
    "ADBE": "Adobe",
    "PEP": "PepsiCo",
    "AMD": "Advanced Micro Devices",
    "LIN": "Linde",
    "TMUS": "T-Mobile US",
    "CSCO": "Cisco",
    "INTU": "Intuit",
    "QCOM": "Qualcomm",
    "TXN": "Texas Instruments",
    "AMGN": "Amgen",
    "ISRG": "Intuitive Surgical",
    "AMAT": "Applied Materials",
    "HON": "Honeywell",
    "BKNG": "Booking Holdings",
    "VRTX": "Vertex Pharmaceuticals",
    "ADP": "Automatic Data Processing",
    "MU": "Micron Technology",
    "PANW": "Palo Alto Networks",
    "REGN": "Regeneron",
    "GILD": "Gilead Sciences",
    "ADI": "Analog Devices",
    "LRCX": "Lam Research",
    "MELI": "MercadoLibre",
    "SBUX": "Starbucks",
    "KLAC": "KLA Corporation",
    "SNPS": "Synopsys",
    "CDNS": "Cadence Design",
    "PYPL": "PayPal",
    "MDLZ": "Mondelez",
    "CRWD": "CrowdStrike",
    "MAR": "Marriott",
    "CTAS": "Cintas",
    "ORLY": "O'Reilly Automotive",
    "ASML": "ASML Holding",
    "NXPI": "NXP Semiconductors",
    "ABNB": "Airbnb",
    "PDD": "PDD Holdings",
    "CEG": "Constellation Energy",
    "MRVL": "Marvell Technology",
    "WDAY": "Workday",
    "ADSK": "Autodesk",
    "FTNT": "Fortinet",
    "DASH": "DoorDash",
    "ROP": "Roper Technologies",
    "TTD": "The Trade Desk",
    "CHTR": "Charter Communications",
    "MNST": "Monster Beverage",
    "PCAR": "PACCAR",
    "CPRT": "Copart",
    "KDP": "Keurig Dr Pepper",
    "PAYX": "Paychex",
    "ODFL": "Old Dominion Freight",
    "AEP": "American Electric Power",
    "ROST": "Ross Stores",
    "FANG": "Diamondback Energy",
    "KHC": "Kraft Heinz",
    "FAST": "Fastenal",
    "EA": "Electronic Arts",
    "VRSK": "Verisk Analytics",
    "CTSH": "Cognizant",
    "GEHC": "GE HealthCare",
    "DDOG": "Datadog",
    "EXC": "Exelon",
    "XEL": "Xcel Energy",
    "CCEP": "Coca-Cola Europacific",
    "LULU": "Lululemon",
    "IDXX": "IDEXX Laboratories",
    "TTWO": "Take-Two Interactive",
    "CSGP": "CoStar Group",
    "ANSS": "Ansys",
    "ON": "ON Semiconductor",
    "ZS": "Zscaler",
    "WBD": "Warner Bros Discovery",
    "DXCM": "Dexcom",
    "BIIB": "Biogen",
    "GFS": "GlobalFoundries",
    "MDB": "MongoDB",
    "ARM": "Arm Holdings",
    "SMCI": "Super Micro Computer",
    "APP": "AppLovin",
    "MSTR": "MicroStrategy",
    "CDW": "CDW Corporation",
    "TEAM": "Atlassian",
    "PLTR": "Palantir",
    "ABBV": "AbbVie",
    "AXON": "Axon Enterprise",
    "TER": "Teradyne",
    "BKR": "Baker Hughes",
    "GRAB": "Grab Holdings",
}
